os:
  - linux
  # - osx
sudo: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="iojs-1"
  - TRAVIS_NODE_VERSION="iojs-2"
  - TRAVIS_NODE_VERSION="iojs-3"
  - TRAVIS_NODE_VERSION="4.0"
  - TRAVIS_NODE_VERSION="5.0"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm --version
  - phantomjs --version
  - npm install
script:
  - npm test
  - phantomjs bin/wavedrom-cli.js -i test/src/step4.js -p step4.png -s step4.svg
  - wc -c step4.svg
