environment:
  matrix:
    - nodejs_version: 5
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - appveyor DownloadFile https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip
  - 7z e phantomjs-2.1.1-windows.zip
  - dir

build: off
