environment:
  matrix:
    - nodejs_version: 5
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - appveyor DownloadFile https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip
  - 7z -y x phantomjs-2.1.1-windows.zip
  - dir
  - mklink /D phantomjs phantomjs-2.1.1-windows
  - dir
  - dir phantomjs
  - phantomjs\bin\phantomjs --version
  - node_modules\.bin\browserify --standalone argumist src\p2_src.js > p2.js
  - node_modules\.bin\browserify --standalone WaveDrom src\p4_src.js > p4.js
  - copy src\p1.js+p2.js+src\p3.js+p4.js+src\p5.js wavedrom-cli.js
  - dir
  - phantomjs\bin\phantomjs wavedrom-cli.js -i test\src\step4.js -p step4.png -s step4.svg
  - dir

build: off
